#TEST users TABLE

### Tampilkan semua data dari tabel users
GET http://localhost:5000/users
Authorization: Bearer 


### Tampilkan data tabel users berdasarkan id
GET http://localhost:5000/users/4
Authorization: Bearer 

### Menambahkan data ke tabel users
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "desti",
    "email": "penyimpananlaptop127@gmail.com",
    "password": "Desti60!",
    "confPassword": "Desti60!",
    "first_name": "destiandira",
    "last_name": "rakhadian"
}

### Menambahkan data admin
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "admin",
    "email": "dwiyantidevina@gmail.com",
    "password": "Admin1234#",
    "confPassword": "Admin1234#",
    "first_name": "Admin",
    "last_name": "1",
    "role": "admin"
}

### Mengupdate data dari tabel users berdasarkan id
PUT http://localhost:5000/users/1
Content-Type: application/json
Authorization: Bearer 

{
    "username": "andi",
    "email": "andiramlihidayat@gmail.com",
    "first_name": "Andi",
    "last_name": "Ramli Hidayat"
}

### Mengupdate password
PATCH http://localhost:5000/users/update-password/5
Content-Type: application/json
Authorization: Bearer 

{
    "currentPassword": "123456789",
    "newPassword": "1234567890",
    "confNewPassword": "1234567890"
}

### Hapus data dari tabel users berdasarkan id
DELETE http://localhost:5000/users/2
Authorization: Bearer 

### Login WITH USERNAME
POST http://localhost:5000/login/
Content-Type: application/json

{
    "identifier": "desti",
    "password": "Desti60!"
}

### Login WITH USERNAME
POST http://localhost:5000/login/
Content-Type: application/json

{
    "identifier": "devinadwi",
    "password": "NewPassword123!"
}

### Login ADMIN
POST http://localhost:5000/login/
Content-Type: application/json

{
    "identifier": "admin",
    "password": "Admin1234#"
}

### Login with EMAIL
POST http://localhost:5000/login/
Content-Type: application/json

{
    "identifier": "berkashandphone@gmail.com",
    "password": "0987654321"
}

### REFRESH TOKEN
POST http://localhost:5000/refresh-token

### Logout
POST http://localhost:5000/logout

### Forgot Password
POST http://localhost:5000/forgot-password
Content-Type: application/json

{
    "email": "devinadwiyanti@mail.ugm.ac.id"
}

### Reset Password
POST http://localhost:5000/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkZXZpbmFkd2l5YW50aUBtYWlsLnVnbS5hYy5pZCIsImlhdCI6MTcyMTM2MDAyMywiZXhwIjoxNzIxMzYzNjIzfQ.5dbJvIhpxSDonK8qFBjL2q68WdeAjeQNyWF4-0RXIwk
Content-Type: application/json

{
    "newPassword": "NewPassword123!",
    "confNewPassword": "NewPassword123!"
}

### RESEND VERIFY EMAIL
POST http://localhost:5000/resend-verification-email
Content-Type: application/json

{
    "email": "berkashandphone@gmail.com"
}
