#TEST users TABLE

### Tampilkan semua data dari tabel users
GET http://localhost:5000/users
Authorization: Bearer 


### Tampilkan data tabel users berdasarkan id
GET http://localhost:5000/users/5

### Menambahkan data ke tabel users
POST http://localhost:5000/users/
Content-Type: application/json

{
    "username": "desti",
    "email": "penyimpananlaptop127@gmail.com",
    "password": "Desti60!",
    "confPassword": "Desti60!",
    "first_name": "destiandira",
    "last_name": "rakhadian"
}

### Mengupdate data dari tabel users berdasarkan id
PATCH http://localhost:5000/users/5
Content-Type: application/json

{
    "username": "andi",
    "email": "andiramlihidayat@gmail.com",
    "first_name": "Andi",
    "last_name": "Ramli Hidayat"
}

### Mengupdate password
PATCH http://localhost:5000/users/5/password
Content-Type: application/json

{
    "currentPassword": "123456789",
    "newPassword": "1234567890",
    "confNewPassword": "1234567890"
}

### Hapus data dari tabel users berdasarkan id
DELETE http://localhost:5000/users/2

### Login WITH USERNAME
POST http://localhost:5000/login/
Content-Type: application/json

{
    "identifier": "devin",
    "password": "123456789"
}

### Login WITH USERNAME
POST http://localhost:5000/login/
Content-Type: application/json

{
    "identifier": "devinadwi",
    "password": "NewPassword123!"
}

### Login WITH EMAIL
POST http://localhost:5000/login/
Content-Type: application/json

{
    "identifier": "yulianurazizah@gmail.com",
    "password": "0987654321"
}

### REFRESH TOKEN
GET http://localhost:5000/token

### Logout
DELETE http://localhost:5000/logout

### Forgot Password
POST http://localhost:5000/forgot-password
Content-Type: application/json

{
    "email": "devinadwiyanti@mail.ugm.ac.id"
}

### Reset Password
POST http://localhost:5000/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkZXZpbmFkd2l5YW50aUBtYWlsLnVnbS5hYy5pZCIsImlhdCI6MTcyMTM2MDAyMywiZXhwIjoxNzIxMzYzNjIzfQ.5dbJvIhpxSDonK8qFBjL2q68WdeAjeQNyWF4-0RXIwk
Content-Type: application/json

{
    "newPassword": "NewPassword123!",
    "confNewPassword": "NewPassword123!"
}

